# -*- coding: utf-8 -*-
"""multilingual-calibration-gptq

Automatically generated by Colab.

"""

import os
from dotenv import load_dotenv

import torch

import numpy as np
import pandas as pd

from transformers import AutoTokenizer, AutoModelForCausalLM
from datasets import load_dataset
from gptqmodel import GPTQModel, QuantizeConfig

from transformers import AutoTokenizer
from huggingface_hub import create_repo
from huggingface_hub import HfApi

# Argument
import argparse

parser = argparse.ArgumentParser("args_gptq")
parser.add_argument("--model_id", type=str)
parser.add_argument("--lang", type=str)
parser.add_argument("--bit", type=int)
parser.add_argument("--nsamples", type=int)
parser.add_argument("--random_seed", type=int, default=1234)

"""# Parameter"""

load_dotenv()

if "HF_KEY" not in os.environ:
    raise EnvironmentError("HF_KEY environment variable is not defined. Please set it before running the application.")
if "WANDB_KEY" not in os.environ:
    raise EnvironmentError("WANDB_KEY environment variable is not defined. Please set it before running the application.")

hf_key = os.environ["HF_KEY"]
wandb_key = os.environ["WANDB_KEY"]

device = 'cuda' if torch.cuda.is_available() else 'cpu'

args = parser.parse_args()
model_id = args.model_id
lang = args.lang
bit = args.bit
nsamples = args.nsamples
random_seed = args.random_seed

lang_lst = ["English",
            "Indonesian",
             "Tamil",
             "Swahili",
             "Chinese"]
ISO_3_lst = ["eng_Latn",
             "ind_Latn",
             "tam_Taml",
             "swh_Latn",
             "cmn_Hans"]
ISO_2_lst = ["en",
             "id",
             "ta",
             "sw",
             "zh"]

ISO_3 = ISO_3_lst[lang_lst.index(lang)]
print(f"lang {lang} bit {bit}")

dataset_split = "dev"

dataset_id = "openlanguagedata/flores_plus"

# Quantization
quantization_technique = "gptq"
bit_lst = [4, 8]

if not os.path.exists("./output"):
    os.makedirs("./output")
output_path_gptq = f"./output/{model_id.split('/')[-1]}_{quantization_technique}_{{bit}}bit_{{lang}}"

## Calibration size
SYMMETRY = False
GROUP_SIZE=128
NUM_CALIBRATION_SAMPLES=nsamples
MAX_SEQUENCE_LENGTH=2048

# huggingface
output_huggingface_gptq = f"fifrio/{model_id.split('/')[-1]}-{quantization_technique}-{{bit}}bit-calibration-{{lang}}{'-128samples' if NUM_CALIBRATION_SAMPLES == 128 else ''}{('-' + str(random_seed) + 'randomseed') if random_seed != 1234 else ''}"

"""# Looping"""

#for bit in bit_lst:
if __name__ == "__main__":
    for j in range(1):
    #for lang, ISO_3 in zip(lang_lst, ISO_3_lst):
        """## Calibration data

        > https://huggingface.co/datasets/cambridgeltl/xcopa
        >
        > https://huggingface.co/datasets/Muennighoff/xwinograd
        >
        > https://huggingface.co/datasets/juletxara/xstory_cloze
        """

        tokenizer = AutoTokenizer.from_pretrained(model_id, token=hf_key)
        # model = AutoModelForCausalLM.from_pretrained(model_id, device_map=device, token=hf_key)

        # Load dataset.
        def prepare_calibration_dataset(model_id, nsamples, seed, seqlen):
            from datasets import load_dataset
            # use the parameters from script arguments
            traindata = load_dataset(dataset_id, ISO_3, split="dev", token=hf_key)
            # testdata = load_dataset('wikitext', 'wikitext-2-raw-v1', split='test')

            from transformers import AutoTokenizer 
            tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=False if "aya" not in model_id else True)
            trainenc = tokenizer("\n\n".join(traindata['text']), return_tensors='pt')
            # testenc = tokenizer("\n\n".join(testdata['text']), return_tensors='pt')
            import random
            random.seed(seed)
            trainloader = []
            for _ in range(nsamples):
                i = random.randint(0, trainenc.input_ids.shape[1] - seqlen - 1)
                j = i + seqlen
                inp = trainenc.input_ids[:, i:j]
                tar = inp.clone()  #unshifted
                tar[:, :-1] = -100  #only last token contributes to loss
                trainloader.append(tokenizer.decode(inp[0].tolist(), skip_special_tokens=True))
            # return trainloader, testenc
            return trainloader
        
        # ds = load_dataset(dataset_id, ISO_3, split="dev", token=hf_key)
        # ds = ds.shuffle(seed=42)
        train_loader = prepare_calibration_dataset(model_id, NUM_CALIBRATION_SAMPLES, random_seed, MAX_SEQUENCE_LENGTH)

        def chat_template(text):
            return [
                {"role": "user", "content": text},
        ]

        # Preprocess the data into the format the model is trained with.
        def preprocess(example):
            return {"text": tokenizer.apply_chat_template(chat_template(example), tokenize=False,)}["text"]
            # return {"text": example["text"]}
        train_loader = list(map(preprocess, train_loader))

        """## GPTQ"""

        quant_config = QuantizeConfig(bits=bit, group_size=GROUP_SIZE, sym=SYMMETRY, lm_head=False, device=device)
        model = GPTQModel.load(model_id, quant_config, token=hf_key)

        model.quantize(train_loader, batch_size=1)
        model.save(output_path_gptq.format(bit=bit, lang=lang))

        """# Upload to Huggingface"""

        create_repo(output_huggingface_gptq.format(bit=bit, lang=lang), repo_type="model", token=hf_key)

        api = HfApi(token=hf_key)

        api.upload_folder(
            folder_path=output_path_gptq.format(bit=bit, lang=lang),
            repo_id=output_huggingface_gptq.format(bit=bit, lang=lang),
            repo_type="model",
        )

