[workspace]
channels = ["conda-forge"]
name = "multilingual-calibration-study"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "<=3.12.11"
numpy = "==1.26.4"
fsspec = "==2025.3.0"

[pypi-dependencies]
python-dotenv = "==1.1.1"
pandas = "<=2.2.2"
optimum = "==1.27.0"
transformers = "==4.56.0"
huggingface_hub = "==0.35.0"
datasets = "==3.6.0"
protobuf = "==5.29.3"
lm-eval = ">=0.4.9.1"
pytablewriter = "<=1.2.1"
wandb = "<=0.22.1"

aiohttp = "==3.12.15"

bitsandbytes = ">=0.48.1"

logbar = ">=0.0.5"
accelerate = ">=1.10.1"
threadpoolctl = ">=3.6.0"
safetensors = ">=0.6.2"
packaging = ">=24.2"
pillow = ">=11.3.0"
hf-transfer = ">=0.1.9"
random-word = ">=1.0.13"
tokenicer = ">=0.0.5"
wheel = ">=0.45.1"
maturin = ">=1.9.3"
autopep8 = ">=2.3.1"
pytest = ">=8.3.3"
pyyaml = ">=6.0.2"
requests = ">=2.32.3"
tqdm = ">=4.42.1"
hf-xet = ">=1.1.3"
iniconfig = ">=1"
pluggy = ">=1.5"
pygments = ">=2.7.2"
charset_normalizer = ">=2"
idna = ">=2.5"
urllib3 = ">=1.21.1"
certifi = ">=2017.4.17"
device-smi = "==0.4.1"
gptqmodel = "==4.2.0"

vllm = ">=0.11.0"

[pypi-options]
no-build-isolation = ["gptqmodel"]

[feature.gpu.system-requirements]
cuda = "12.8"

[feature.gpu.pypi-options]
dependency-overrides = { numpy = "==1.26.4" }

[feature.gpu.pypi-dependencies]
torch = { version = ">=2.7.0", index = "https://download.pytorch.org/whl/cu128"}
torchvision = { version = ">=0.22.0", index = "https://download.pytorch.org/whl/cu128" }

[feature.cpu.pypi-dependencies]
torch = { version = ">=2.7.0", index = "https://download.pytorch.org/whl/cpu"}
torchvision = { version = ">=0.22.0", index = "https://download.pytorch.org/whl/cpu" }

[feature.cpu.pypi-options]
dependency-overrides = { numpy = "==1.26.4" }

[environments]
cpu = ["cpu"]
gpu = ["gpu"]
default = ["gpu"]
