[workspace]
channels = ["conda-forge"]
name = "multilingual-calibration-study"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "<=3.12.11"
numpy = "==1.26.4"
fsspec = "==2025.3.0"

[pypi-dependencies]
python-dotenv = "==1.1.1"
pandas = "<=2.2.2"
transformers = "==4.51.0"
huggingface_hub = "==0.35.0"
datasets = "==3.6.0"
protobuf = "==5.29.3"
lm-eval = "<=0.4.9.1"
wandb = "<=0.22.1"

aiohttp = "==3.12.15"

bitsandbytes = ">=0.48.1"

logbar = ">=0.0.5"
accelerate = ">=0.26.0"
threadpoolctl = ">=3.6.0"
safetensors = ">=0.6.2"

sentencepiece = "==0.2.1"
rouge
gekko
peft>=0.5.0

jieba==0.42.1
jsonlines==4.0.0
matplotlib==3.8.3
nagisa==0.2.11
numpy==1.26.4
omegaconf==2.3.0
openai==1.30.3
packaging==24.0
pandas==2.2.2
pycountry==23.12.11
pytablewriter==1.2.0
pytest==8.2.1
Requests==2.32.2
rouge_score==0.1.2
sacrebleu==1.5.0
scikit_learn==1.4.1.post1
scipy==1.13.1
sqlitedict==2.1.0
tqdm==4.66.2
transformers==4.35.0
zstandard==0.22.0

[feature.gpu.system-requirements]
cuda = "12.8"

[feature.gpu.pypi-options]
dependency-overrides = { numpy = "==1.26.4" }

[feature.gpu.pypi-dependencies]
torch = { version = ">=2.7.0", index = "https://download.pytorch.org/whl/cu128"}
torchvision = { version = ">=0.22.0", index = "https://download.pytorch.org/whl/cu128" }

[feature.cpu.pypi-dependencies]
torch = { version = ">=2.7.0", index = "https://download.pytorch.org/whl/cpu"}
torchvision = { version = ">=0.22.0", index = "https://download.pytorch.org/whl/cpu" }

[feature.cpu.pypi-options]
dependency-overrides = { numpy = "==1.26.4" }

[environments]
cpu = ["cpu"]
gpu = ["gpu"]
default = ["gpu"]
