# -*- coding: utf-8 -*-
"""multilingual-calibration-gptq

Automatically generated by Colab.
"""

import os
from dotenv import load_dotenv

import torch

import numpy as np
import pandas as pd

from huggingface_hub import create_repo
from huggingface_hub import HfApi

# Argument
import argparse

parser = argparse.ArgumentParser("args_gptq")
parser.add_argument("--model_id", type=str)
parser.add_argument("--lang", type=str)
parser.add_argument("--bit", type=str)
parser.add_argument("--nsamples", type=int)
parser.add_argument("--save_path", type=str)
parser.add_argument("--seed", type=int, default=1234)

"""# Parameter"""

load_dotenv()

if "HF_KEY" not in os.environ:
    raise EnvironmentError("HF_KEY environment variable is not defined. Please set it before running the application.")
if "WANDB_KEY" not in os.environ:
    raise EnvironmentError("WANDB_KEY environment variable is not defined. Please set it before running the application.")

hf_key = os.environ["HF_KEY"]
wandb_key = os.environ["WANDB_KEY"]

device = 'cuda' if torch.cuda.is_available() else 'cpu'

args = parser.parse_args()
model_id = args.model_id
lang = args.lang.split("_")[-1] if args.lang.startswith("flores") else args.lang 
bit = int(args.bit[1:]) if args.bit.startswith("q") else int(args.bit)
nsamples = args.nsamples
random_seed = args.seed

# Model
model_id = model_id

lang_lst = ["English",
            "Indonesian",
             "Tamil",
             "Swahili",
             "Chinese"]
ISO_3_lst = ["eng_Latn",
             "ind_Latn",
             "tam_Taml",
             "swh_Latn",
             "cmn_Hans"]
ISO_2_lst = ["en",
             "id",
             "ta",
             "sw",
             "zh"]

ISO_3 = ISO_3_lst[lang_lst.index(lang)]
print(f"lang {lang} bit {bit}")

dataset_split = "dev"

dataset_id = "openlanguagedata/flores_plus"

# Quantization
quantization_technique = "tacq"
bit_lst = [4, 8]

output_path_gptq = args.save_path

## Calibration size
SYMMETRY = False
GROUP_SIZE=128
NUM_CALIBRATION_SAMPLES=nsamples
MAX_SEQUENCE_LENGTH=2048

# huggingface
output_huggingface_gptq = f"fifrio/{model_id.split('/')[-1]}-{quantization_technique}-{{bit}}bit-calibration-{{lang}}{'-128samples' if NUM_CALIBRATION_SAMPLES == 128 else ''}{('-' + str(random_seed) +'randomseed') if random_seed != 1234 else ''}"

"""# Looping"""

#for bit in bit_lst:
for i in range(1):
    for j in range(1):
    #for lang, ISO_3 in zip(lang_lst, ISO_3_lst):
        """# Upload to Huggingface"""

        # create_repo(output_huggingface_gptq.format(bit=bit, lang=lang), repo_type="model", token=hf_key)

        api = HfApi(token=hf_key)

        api.upload_folder(
            folder_path=output_path_gptq,
            repo_id=output_huggingface_gptq.format(bit=bit, lang=lang),
            repo_type="model",
        )

