[workspace]
channels = ["conda-forge"]
name = "multilingual-calibration-study"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "<=3.12.11"
numpy = "==1.26.4"
fsspec = "==2025.3.0"

[pypi-dependencies]
python-dotenv = "==1.1.1"
pandas = "<=2.2.2"
optimum = "==1.27.0"
transformers = "==4.52.0"
huggingface_hub = "==0.35.0"
datasets = "==3.6.0"
protobuf = "==5.29.3"
lm-eval = ">=0.4.9.1"
pytablewriter = "<=1.2.1"
wandb = "<=0.22.0"

aiohttp = "==3.12.15"

accelerate = "==0.32.1"
anyio = "==4.4.0"
argon2-cffi = "==23.1.0"
argon2-cffi-bindings = "==21.2.0"
arrow = "==1.3.0"
astroid = "==3.3.9"
asttokens = "==2.4.1"
async-lru = "==2.0.4"
attrs = "==23.2.0"
autopep8 = "==2.3.2"
Babel = "==2.15.0"
beautifulsoup4 = "==4.12.3"
bitsandbytes = "==0.43.1"
bleach = "==6.1.0"
blessed = "==1.20.0"
certifi = "==2024.6.2"
cffi = "==1.16.0"
charset-normalizer = "==3.3.2"
click = "==8.1.7"
comm = "==0.2.2"
contourpy = "==1.2.1"
cycler = "==0.12.1"
debugpy = "==1.8.1"
decorator = "==5.1.1"
defusedxml = "==0.7.1"
dill = "==0.3.8"
docker-pycreds = "==0.4.0"
docstring_parser = "==0.16"
evaluate = "==0.4.2"
executing = "==2.0.1"
fastjsonschema = "==2.19.1"
fonttools = "==4.53.0"
fqdn = "==1.5.1"
frozenlist = "==1.4.1"
gitdb = "==4.0.11"
GitPython = "==3.1.43"
gpustat = "==1.1.1"
h11 = "==0.14.0"
httpcore = "==1.0.5"
httpx = "==0.27.0"
idna = "==3.7"
ijson = "==3.3.0"
ipykernel = "==6.29.4"
ipython = "==8.25.0"
ipywidgets = "==8.1.3"
isoduration = "==20.11.0"
isort = "==6.0.1"
jedi = "==0.19.1"
Jinja2 = "==3.1.4"
joblib = "==1.4.2"
json5 = "==0.9.25"
jsonpointer = "==2.4"
jsonschema = "==4.22.0"
jsonschema-specifications = "==2023.12.1"
jupyter = "==1.0.0"
jupyter-console = "==6.6.3"
jupyter-events = "==0.10.0"
jupyter-lsp = "==2.2.5"
jupyter_client = "==8.6.2"
jupyter_core = "==5.7.2"
jupyter_server = "==2.14.1"
jupyter_server_terminals = "==0.5.3"
jupyterlab = "==4.2.1"
jupyterlab_pygments = "==0.3.0"
jupyterlab_server = "==2.27.2"
jupyterlab_widgets = "==3.0.11"
kaleido = "==0.2.1"
kiwisolver = "==1.4.5"
line_profiler = "==4.1.3"
markdown-it-py = "==3.0.0"
MarkupSafe = "==2.1.5"
matplotlib = "==3.8.0"
matplotlib-inline = "==0.1.7"
mccabe = "==0.7.0"
mdurl = "==0.1.2"
mistune = "==3.0.2"
mpmath = "==1.3.0"
multidict = "==6.0.5"
multiprocess = "==0.70.16"
nbclient = "==0.10.0"
nbconvert = "==7.16.4"
nbformat = "==5.10.4"
nest-asyncio = "==1.6.0"
networkx = "==3.3"
nltk = "==3.9.1"
notebook = "==7.2.0"
notebook_shim = "==0.2.4"
overrides = "==7.7.0"
packaging = "==24.0"
pandocfilters = "==1.5.1"
parso = "==0.8.4"
peft = "==0.11.1"
pexpect = "==4.9.0"
pillow = "==10.3.0"
platformdirs = "==4.2.2"
plotly = "==5.24.1"
prometheus_client = "==0.20.0"
prompt_toolkit = "==3.0.46"
psutil = "==5.9.8"
ptyprocess = "==0.7.0"
PuLP = "==2.9.0"
pure-eval = "==0.2.2"
py3nvml = "==0.2.7"
pyarrow = "==16.1.0"
pyarrow-hotfix = "==0.6"
pycodestyle = "==2.13.0"
pycparser = "==2.22"
Pygments = "==2.18.0"
pylint = "==3.3.6"
pyparsing = "==3.1.2"
python-dateutil = "==2.9.0.post0"
python-json-logger = "==2.0.7"
pytz = "==2024.1"
PyYAML = "==6.0.1"
pyzmq = "==26.0.3"
qtconsole = "==5.5.2"
QtPy = "==2.4.1"
referencing = "==0.35.1"
regex = "==2024.5.15"
requests = "==2.32.3"
rfc3339-validator = "==0.1.4"
rfc3986-validator = "==0.1.1"
rich = "==13.7.1"
rpds-py = "==0.18.1"
safetensors = "==0.4.5"
scikit-learn = "==1.5.1"
scipy = "==1.14.0"
seaborn = "==0.13.2"
Send2Trash = "==1.8.3"
sentencepiece = "==0.2.0"
sentry-sdk = "==2.12.0"
setproctitle = "==1.3.3"
sh = "==2.1.0"
shtab = "==1.7.1"
six = "==1.16.0"
smmap  ="==5.0.1"
sniffio = "==1.3.1"
soupsieve = "==2.5"
sqlparse = "==0.5.3"
stack-data = "==0.6.3"
tenacity = "==9.0.0"
terminado = "==0.18.1"
threadpoolctl = "==3.5.0"
tinycss2 = "==1.3.0"
tomlkit = "==0.13.2"
torch-pruning = "==1.5.1"
tornado = "==6.4"
tqdm = "==4.66.4"
traitlets = "==5.14.3"
trl = "==0.9.6"
types-python-dateutil = "==2.9.0.20240316"
typing_extensions = "==4.12.2"
tyro = "==0.8.5"
tzdata = "==2024.1"
uri-template = "==1.3.0"
urllib3 = "==2.2.1"
wcwidth = "==0.2.13"
webcolors = "==1.13"
webencodings = "==0.5.1"
websocket-client = "==1.8.0"
widgetsnbextension = "==4.0.11"
xmltodict = "==0.14.2"

[feature.gpu.system-requirements]
cuda = "12.8"

[feature.gpu.pypi-options]
dependency-overrides = { numpy = "==1.26.4" }

[feature.gpu.pypi-dependencies]
torch = { version = ">=2.8.0", index = "https://download.pytorch.org/whl/cu128"}
torchvision = { version = ">=0.22.0", index = "https://download.pytorch.org/whl/cu128" }

[feature.cpu.pypi-dependencies]
torch = { version = ">=2.7.0", index = "https://download.pytorch.org/whl/cpu"}
torchvision = { version = ">=0.22.0", index = "https://download.pytorch.org/whl/cpu" }

[feature.cpu.pypi-options]
dependency-overrides = { numpy = "==1.26.4" }

[environments]
cpu = ["cpu"]
gpu = ["gpu"]
default = ["gpu"]
